services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./utils/recipes/Dockerfile_client
    volumes:
      - ./utils/storage/client/Taskfile.yaml:/root/Taskfile.yaml
    tty: true
    networks:
        - waf-demo
  server:
    container_name: server
    image: dunglas/frankenphp
    volumes:
      - ./utils/storage/server/app:/app/public
    ports:
      - "8001:80"
    environment:
      - SERVER_NAME=:80
    networks:
        - waf-demo
  secured-server:
    container_name: secured-server
    build:
      context: .
      dockerfile: ./utils/recipes/Dockerfile_secured_server
    volumes:
      - ./utils/storage/server/app:/app/public
    ports:
      - "8002:80"
    environment:
      - SERVER_NAME=:80
    networks:
      - waf-demo
networks:
  waf-demo: